// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwfpqxobbwbmhlxhisuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZnBxeG9iYndibWhseGhpc3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTE3MzksImV4cCI6MjA1OTgyNzczOX0.59j4oiuO3kJG08Xv7I8MFLgvkqHydqc_mDt4P0rpc7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);